version: '3.8'

services:
  code2seq_comments:
    build:
      context: ""
      dockerfile: Dockerfile
    image: ciselab/code2seq:latest
    volumes:
      # source on local machine: place in container
      - ./models:/app/code2seq/models
      - ./datasets/funcom/raw:/app/code2seq/datasets/funcom/raw:ro
      - ./datasets/funcom/preprocessed:/app/code2seq/datasets/funcom/preprocessed:rw
      
    environment:
      dataset: "funcom"
    # Preprocessing variables
      preprocess: true
      includeComments: true
      excludeStopwords: true
      useTfidf: false 
      numberOfTfidfKeywords: "50"
    # Training variables
      train: true
      continueTrainingFromCheckpoint: false
    # Evaluation variables
    # add more flags here

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
