version: '3.8'

services:
  code2seq_comments:
    build:
      context: ""
      dockerfile: Dockerfile
    image: ciselab/code2seq:latest
    volumes:
      # source on local machine: place in container
      - ./models:/app/code2seq/models
      - ./datasets/codesearchnet/raw:/app/code2seq/datasets/codesearchnet/raw:ro
      - ./datasets/codesearchnet/preprocessed:/app/code2seq/datasets/codesearchnet/preprocessed:rw
      
    environment:
      dataset: "codesearchnet"
    # Preprocessing variables
      preprocess: true
      includeComments: false
      excludeStopwords: false
      useTfidf: false
      numberOfTfidfKeywords: "569"
    # Training variables
      train: true
      continueTrainingFromCheckpoint: false
    # Evaluation variables
    # add more flags here

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]