version: '3.8'

services:
  code2seq_comments:
    build:
      context: ""
      dockerfile: Dockerfile
    image: ciselab/code2seq:latest
    volumes:
      # source on local machine: place in container
      - ./models:/app/code2seq/models
      - ./datasets/codesearchnet/raw:/app/code2seq/datasets/codesearchnet/raw:ro
      - ./datasets/codesearchnet/preprocessed:/app/code2seq/datasets/codesearchnet/preprocessed:rw
      
    environment:
      dataset: "codesearchnet"
      variant: "comments"
    # Preprocessing variables
      preprocess: true
      includeComments: true
      excludeStopwords: true
      useTfidf: false 
      numberOfTfidfKeywords: "50"
    # Training variables
      train: true
      # There has to ba an existing model for the following to work
      continueTrainingFromCheckpoint: false

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
